# Generated by Django 4.2.7 on 2023-12-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="ndc_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
